/* Temp catalog. Placeholder copy and example.com stubs, not curriculum picks. */
window.ROADMAP = {
  nodes: [
    {
      id: "enter",
      title: "Enter the path",
      stage: "start",
      x: 40,
      y: 244,
      kinds: ["skill"],
      tracks: [],
      level: "beginner",
      briefing: "You are at the start. Two skills first, then the gate cert. Not a job track yet.",
      why: "Order matters. Fundamentals before certs, certs before applications.",
      next: ["computer-fundamentals", "network-fundamentals"],
      links: [{ label: "Temp: how to begin", href: "https://example.com/temp-start", temp: true }]
    },
    {
      id: "computer-fundamentals",
      title: "Computer fundamentals",
      stage: "skills",
      x: 300,
      y: 64,
      kinds: ["skill"],
      tracks: [],
      level: "beginner",
      briefing: "How computers actually work. Hardware, operating systems, and the command line.",
      why: "Everything later assumes this. Skipping it means relearning it under pressure.",
      next: ["security-plus"],
      links: [{ label: "Temp: Professor Messer A+ core", href: "https://example.com/temp-computer", temp: true }]
    },
    {
      id: "network-fundamentals",
      title: "Network fundamentals",
      stage: "skills",
      x: 300,
      y: 444,
      kinds: ["skill"],
      tracks: [],
      level: "beginner",
      briefing: "How machines talk. TCP/IP, DNS, and what a packet does on the wire.",
      why: "Security work is network work. This is the other half of the starting fork.",
      next: ["security-plus"],
      links: [{ label: "Temp: Network+ outline", href: "https://example.com/temp-network", temp: true }]
    },
    {
      id: "security-plus",
      title: "Security+",
      stage: "certs",
      x: 580,
      y: 244,
      kinds: ["cert"],
      tracks: [],
      level: "beginner",
      briefing: "The gate cert. Broad vocabulary across threats, controls, and operations.",
      why: "Gate cert after fundamentals. Not the last cert, and not a specialty.",
      next: ["first-labs", "practical-cert"],
      links: [{ label: "Temp: CompTIA Security+ exam", href: "https://example.com/temp-secplus", temp: true }]
    },
    {
      id: "first-labs",
      title: "First lab hours",
      stage: "labs",
      x: 860,
      y: 64,
      kinds: ["lab"],
      tracks: [],
      level: "beginner",
      briefing: "Hands on keyboards. Guided labs that prove you can do the work, not just name it.",
      why: "You already have Security+. Time in labs beats another trivia exam.",
      next: ["portfolio-project"],
      links: [{ label: "Temp: intro SOC / fundamentals path", href: "https://example.com/temp-labs", temp: true }]
    },
    {
      id: "practical-cert",
      title: "Practical cert",
      stage: "certs",
      x: 860,
      y: 444,
      kinds: ["cert"],
      tracks: [],
      level: "intermediate",
      briefing: "A hands-on cert that tests doing, not memorizing. One is enough for now.",
      why: "You already have Security+. Do not sit another trivia exam.",
      next: ["portfolio-project"],
      links: [{ label: "Temp: first practical cert", href: "https://example.com/temp-practical", temp: true }]
    },
    {
      id: "portfolio-project",
      title: "Portfolio project",
      stage: "break-in",
      x: 1140,
      y: 244,
      kinds: ["project"],
      tracks: [],
      level: "intermediate",
      briefing: "One home-lab project, written up. Something a hiring manager can read in five minutes.",
      why: "Proof of work. Labs without a writeup do not travel.",
      next: ["resume-apps"],
      links: [{ label: "Temp: home-lab brief", href: "https://example.com/temp-project", temp: true }]
    },
    {
      id: "resume-apps",
      title: "Resume and applications",
      stage: "break-in",
      x: 1420,
      y: 244,
      kinds: ["skill"],
      tracks: [],
      level: "intermediate",
      briefing: "A tight resume and a steady application habit. Target junior and apprentice roles.",
      why: "The break-in step. Skills without applications do not convert.",
      next: ["soc-l1", "grc-fundamentals"],
      links: [{ label: "Temp: resume teardown notes", href: "https://example.com/temp-resume", temp: true }]
    },
    {
      id: "soc-l1",
      title: "SOC L1",
      stage: "soc",
      x: 1700,
      y: 64,
      kinds: ["skill"],
      tracks: ["soc"],
      level: "intermediate",
      briefing: "First blue-team role. Triage alerts, escalate well, learn the stack.",
      why: "The standard entry point. This community starts people on blue.",
      next: [],
      links: [{ label: "Temp: SOC L1 role notes", href: "https://example.com/temp-soc", temp: true }]
    },
    {
      id: "grc-fundamentals",
      title: "GRC fundamentals",
      stage: "grc",
      x: 1700,
      y: 444,
      kinds: ["skill"],
      tracks: ["grc"],
      level: "intermediate",
      briefing: "Governance, risk, and compliance basics. Frameworks, evidence, and audit language.",
      why: "The other entry rail. Pick it deliberately, not by default.",
      next: [],
      links: [{ label: "Temp: GRC starter", href: "https://example.com/temp-grc", temp: true }]
    }
  ],
  edges: [
    { from: "enter", to: "computer-fundamentals" },
    { from: "enter", to: "network-fundamentals" },
    { from: "computer-fundamentals", to: "security-plus" },
    { from: "network-fundamentals", to: "security-plus" },
    { from: "security-plus", to: "first-labs" },
    { from: "security-plus", to: "practical-cert" },
    { from: "first-labs", to: "portfolio-project" },
    { from: "practical-cert", to: "portfolio-project" },
    { from: "portfolio-project", to: "resume-apps" },
    { from: "resume-apps", to: "soc-l1" },
    { from: "resume-apps", to: "grc-fundamentals" }
  ]
};
